# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Data Science Blog # Make a title for your blog
email: acurtis2001@hotmail.com # Add your email 
description: >- # this means to ignore newlines until "baseurl:"
 Welcome to my blog! I am a senior studying Applied Statistics & Analytics at BYU, and I have created
 this blog as a way to explore data science concepts! Feel free to code along with me as I dive into the
 excitement of webscraping, data wrangling, and exploratory data analysis!
baseurl: "/stat386-projects" # keep this the same or change it to the name of the repository 
url: "https://acurtis2023.github.io" #  change this to "https://<your-github-username>.github.io"
image: "assets/images/alta.jpg"
author: Aubree Curtis
copyright: ALC # Your initials or what you want the copyright to be.  Leave empty for no copyright

# Social media users names.  Leave fields blank that you don't want displayed
twitter_username: 
github_username:  acurtis2023
linkedin_username: aubree-curtis
dribbble_username: 
facebook_username: 
flickr_username:
instagram_username: aubreecurtis
pinterest_username:
youtube_username: 
googleplus_username: 


# Build settings
# removed minima theme to a regular theme
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
